name: 'Publish Bicep Files'
description: 'Publishes all the changed files given as input to the registry given as input'
icon: upload-cloud
inputs:
  tag:
    description: 'tag to publish modules with'
    required: true
  registry: 
    description: 'name of registry to publish the modules to'
    required: true
  changedfiles: 
    description: changed files that need to be uploaded
    required: true
  
runs:
  using: 'node16'
  main: 'index.js'
